# Configuration for https://github.com/crate-ci/typos

[files]

[default]
extend-ignore-re = [
    # Markdown in README.md
    "earchAnd*",
    # release.sh
    "-Prelease-sign-artifacts"
]

[default.extend-words]

[default.extend-identifiers]
